[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "npm ci",
    "npm run build",
    "chmod +x start.sh"
]

[phases.start]
cmd = "./start.sh"

[variables]
PHP_VERSION = "8.2"
NODE_VERSION = "18" 