[phases.build]
cmds = [
    "composer install --optimize-autoloader",
    "npm ci",
    "npm run build"
]

[phases.start]
cmd = "cd public && php -S 0.0.0.0:$PORT"

[variables]
PHP_VERSION = "8.2"
NODE_VERSION = "18" 