[variables]
APP_ENV = "production"
APP_DEBUG = "false"
LOG_CHANNEL = "stderr"
DB_CONNECTION = "sqlite"
DB_DATABASE = "/app/database/database.sqlite"
CACHE_DRIVER = "file"
SESSION_DRIVER = "file"
QUEUE_CONNECTION = "sync"
MAIL_MAILER = "log"
APP_KEY = "base64:mcSE07/xaGmT9Beq4xuzbFsd3SUJJTje8kFpZnUeW3k="

# Empty variables to prevent warnings
DATABASE_URL = ""
DB_URL = ""
MYSQL_ATTR_SSL_CA = ""
AWS_ACCESS_KEY_ID = ""
AWS_SECRET_ACCESS_KEY = ""
AWS_URL = ""
DYNAMODB_ENDPOINT = ""
REDIS_URL = ""
REDIS_USERNAME = ""
REDIS_PASSWORD = ""
DB_CACHE_CONNECTION = ""
DB_CACHE_LOCK_CONNECTION = ""
DB_CACHE_LOCK_TABLE = ""
MEMCACHED_PERSISTENT_ID = ""
MEMCACHED_USERNAME = ""
MEMCACHED_PASSWORD = ""

[phases.setup]
cmds = [
  "mkdir -p database",
  "touch database/database.sqlite",
  "php artisan migrate --force --no-interaction",
  "php artisan config:clear",
  "php artisan cache:clear"
]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader --no-interaction"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public/ public/index.php" 